# Generated by Django 2.1.7 on 2020-02-03 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='second_last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='second_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person_role',
            name='university_career_id',
            field=models.ForeignKey(blank=True, db_column='university_career_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Item_Category'),
        ),
    ]
