# Generated by Django 2.1.7 on 2020-02-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200203_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name_plural': 'Contents'},
        ),
        migrations.AlterModelOptions(
            name='content_media',
            options={'verbose_name': 'Content Media', 'verbose_name_plural': 'Contents Media'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='group_contact',
            options={'verbose_name': 'Group Contact', 'verbose_name_plural': 'Group Contacts'},
        ),
        migrations.AlterModelOptions(
            name='group_event',
            options={'verbose_name': 'Relationship Group Event', 'verbose_name_plural': 'Relationships Group Event'},
        ),
        migrations.AlterModelOptions(
            name='item_category',
            options={'verbose_name': 'Item Category', 'verbose_name_plural': 'Items Category'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name_plural': 'Menus'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'Persons'},
        ),
        migrations.AlterModelOptions(
            name='person_contact',
            options={'verbose_name': 'Person Contact', 'verbose_name_plural': 'Person Contacts'},
        ),
        migrations.AlterModelOptions(
            name='person_media',
            options={'verbose_name': 'Person Media', 'verbose_name_plural': 'Person Medias'},
        ),
        migrations.AlterModelOptions(
            name='person_role',
            options={'verbose_name': 'Relationship Person Role', 'verbose_name_plural': 'Relationships Person Role'},
        ),
        migrations.AlterModelOptions(
            name='person_section',
            options={'verbose_name': 'Relationship Person Section', 'verbose_name_plural': 'Relationships Person Section'},
        ),
        migrations.AlterModelOptions(
            name='requirement',
            options={'verbose_name_plural': 'Requirements'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name_plural': 'Sections'},
        ),
        migrations.AlterModelOptions(
            name='subject_matter',
            options={'verbose_name': 'Subject Matter', 'verbose_name_plural': 'Subject Matters'},
        ),
        migrations.AlterField(
            model_name='content',
            name='description',
            field=models.CharField(max_length=1020),
        ),
    ]
