# Generated by Django 2.1.7 on 2020-02-09 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200207_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirement',
            old_name='subject_matter_requeriment_id',
            new_name='subject_matter_requirement_id',
        ),
    ]
