# Generated by Django 2.1.7 on 2020-02-12 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200209_0122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_Item',
            fields=[
                ('menu_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(blank=True, max_length=1020, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('item_category_id', models.ForeignKey(db_column='item_category_id', on_delete=django.db.models.deletion.PROTECT, to='core.Item_Category')),
            ],
            options={
                'verbose_name_plural': 'Menu Items',
            },
        ),
        migrations.AddField(
            model_name='content',
            name='person_id',
            field=models.ForeignKey(blank=True, db_column='person_id', help_text='The author of the content', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Person'),
        ),
        migrations.AddField(
            model_name='section',
            name='description',
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='academic_period_id',
            field=models.ForeignKey(blank=True, db_column='academic_period_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='academic_period_id_related_name', to='core.Item_Category'),
        ),
        migrations.AlterField(
            model_name='content',
            name='university_career_id',
            field=models.ForeignKey(blank=True, db_column='university_career_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='university_career_id_related_name', to='core.Item_Category'),
        ),
    ]
