# Generated by Django 2.1.7 on 2020-02-14 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200212_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='subject_matter_requirement_id',
            field=models.ForeignKey(db_column='subject_matter_requirement_id', on_delete=django.db.models.deletion.PROTECT, related_name='subject_matter_requirement_id_related_name', to='core.Subject_Matter'),
        ),
    ]
