from rest_framework import routers
from login import views

router = routers.DefaultRouter()
#router.register('login', views.login, name="login")
#router.register('usuario', views.usuario)
router.register('category', views.CategoryViewset)
router.register('item-category', views.ItemCategoryViewset)
router.register('persons', views.PersonsViewset)
router.register('persons-departments', views.Persons_departamentsViewset)
router.register('persons-role', views.Persons_roleViewset)
router.register('persons-media', views.Persons_mediaViewset)
router.register('persons-contact', views.Persons_ContactsViewset)
router.register('subject-matter', views.Subject_matterViewset)
router.register('pre-requirements', views.Pre_requirementsViewset)
router.register('info-site', views.Info_siteViewset)
router.register('content', views.ContentViewset)
router.register('content-media', views.Content_mediaViewset)
router.register('content-info', views.Content_infoViewset)
router.register('menu', views.MenuViewset)
#router.register('titulacion',views.ItemCategoryRolList)
